#!/usr/bin/env python3
"""
Gzip-compress the embedded web UI pages at build time (FEAT-flash-optim).

The web pages (dashboard, editor, system, cli, ota) live as plain .html
source files under web/*.html for readability/editing. This script
compresses each with gzip and writes a generated C header containing the
compressed bytes, which the corresponding web_*.cpp #includes and serves
directly with a "Content-Encoding: gzip" header — the browser decompresses
it, so nothing changes for the user, but the ~178 KB of raw HTML/CSS/JS
that used to sit uncompressed in flash shrinks to ~64 KB compressed.

Regenerated on every build (like build_version.h) — do not hand-edit the
generated headers under include/generated_web/.
"""

import gzip
import os

try:
    Import("env")
    project_root = env.get("PROJECT_DIR")
except Exception:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

PAGES = [
    ("web/dashboard.html", "dashboard_html_gz", "generated_web/dashboard_html_gz.h"),
    ("web/editor.html",    "editor_html_gz",    "generated_web/editor_html_gz.h"),
    ("web/system.html",    "system_html_gz",    "generated_web/system_html_gz.h"),
    ("web/cli.html",       "cli_html_gz",       "generated_web/cli_html_gz.h"),
    ("web/ota.html",       "ota_html_gz",       "generated_web/ota_html_gz.h"),
    ("web/logs.html",      "logs_html_gz",      "generated_web/logs_html_gz.h"),
]

total_raw = 0
total_gz = 0

for src_rel, sym, out_rel in PAGES:
    src_path = os.path.join(project_root, src_rel)
    out_path = os.path.join(project_root, "include", out_rel)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(src_path, "rb") as f:
        raw = f.read()
    compressed = gzip.compress(raw, compresslevel=9)

    total_raw += len(raw)
    total_gz += len(compressed)

    lines = []
    lines.append("/**")
    lines.append(f" * AUTO-GENERATED by scripts/gzip_web_assets.py from {src_rel}")
    lines.append(" * DO NOT EDIT MANUALLY -- edit the .html source and rebuild.")
    lines.append(f" * {len(raw)} bytes raw -> {len(compressed)} bytes gzip")
    lines.append(" */")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append(f"static const uint8_t {sym}[] = {{")
    hex_bytes = ",".join(f"0x{b:02x}" for b in compressed)
    # Wrap at ~120 chars/line so the generated file stays diffable/reviewable
    line = ""
    for chunk in hex_bytes.split(","):
        if len(line) + len(chunk) + 1 > 120:
            lines.append(line + ",")
            line = chunk
        else:
            line = chunk if not line else line + "," + chunk
    if line:
        lines.append(line)
    lines.append("};")
    lines.append(f"static const size_t {sym}_len = sizeof({sym});")
    lines.append("")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

print(f"gzip_web_assets: {total_raw} bytes raw -> {total_gz} bytes gzip "
      f"(saved {total_raw - total_gz} bytes, {100 * total_gz / total_raw:.1f}% of original)")
