/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 2777
#define BUILD_TIMESTAMP "2026-10-05 11:46:44"
#define BUILD_DATE "20261005"
#define GIT_HASH "31a6a23"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
