/**
 * @file build_version.h
 * @brief Auto-generated build information
 *
 * DO NOT EDIT MANUALLY - Generated by generate_build_info.py
 */

#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#define BUILD_NUMBER 2629
#define BUILD_TIMESTAMP "2026-10-02 19:51:08"
#define BUILD_DATE "20261002"
#define GIT_HASH "c54cd2e"
#define GIT_BRANCH "main"

#endif // BUILD_VERSION_H
